-- ══════════════════════════════════════════════════════════════════════════════
-- datos_iniciales.sql  —  Datos mínimos para arrancar el sistema en producción
-- Ejecutar después de crear_bd.sql. Se puede relanzar: limpia y recarga solo
-- Componente, Tecnico y Usuario (no toca tablas operativas).
-- ══════════════════════════════════════════════════════════════════════════════

USE reparaciones;

SET SQL_SAFE_UPDATES  = 0;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Usuario;
TRUNCATE TABLE Tecnico;
TRUNCATE TABLE Componente;

SET FOREIGN_KEY_CHECKS = 1;

-- ── Usuarios iniciales ────────────────────────────────────────────────────────
-- Contraseña por defecto: cambiar tras el primer acceso
INSERT INTO Usuario (NOMBRE_USUARIO, PASSWORD, ROL, ID_TEC)
VALUES ('admin', '$2a$10$89OoWr1AD1dbESqCVGhGVOBWILu0ld117qcCSS68z1dH4k/A7MjBu', 'ADMIN', NULL);


-- ── Componentes (SKUs) ────────────────────────────────────────────────────────

-- Otros
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi8', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi8plus', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroise2020', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroix', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroixr', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroixs', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroixsmax', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi11', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi11pro', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi11promax', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12mini', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12pro', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi12promax', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13mini', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13pro', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi13promax', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14plus', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14pro', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi14promax', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15plus', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15pro', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi15promax', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16e', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16pro', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16promax', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('otroi16plus', 8, 2);

-- Batería
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati8', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati8plus', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batise2020', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batix', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batixr', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batixs', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('batixsmax', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati11', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati11pro', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati11promax', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12mini', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12pro', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati12promax', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13mini', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13pro', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati13promax', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14plus', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14pro', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati14promax', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15plus', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15pro', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati15promax', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16e', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16pro', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16promax', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('bati16plus', 6, 2);

-- Pantalla
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi11negraic', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi11pronegraic', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi11promaxnegraic', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi12negraic', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi12mininegraic', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi12promaxnegraic', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13negraic', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13mininegraic', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13pronegraic', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi13promaxnegraic', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14negraic', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14pronegraic', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14plusnegraic', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi14promaxnegraic', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15negraic', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15plusnegraic', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15pronegraic', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi15promaxnegraic', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16negraic', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16enegraic', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16pronegraic', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16promaxnegraic', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('lcdi16plusnegraic', 7, 2);

-- Cámara
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami8', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami8plus', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camise2020', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camix', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camixr', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camixs', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('camixsmax', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami11', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami11pro', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami11promax', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12mini', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12pro', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami12promax', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13mini', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13pro', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami13promax', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14plus', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14pro', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami14promax', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15plus', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15pro', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami15promax', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16e', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16pro', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16promax', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('cami16plus', 5, 2);

-- Chasis
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8silver', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8gold', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8spacegrey', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8productred', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plussilver', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plusgold', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plusspacegrey', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai8plusproductred', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaise2020black', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaise2020white', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaise2020productred', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsilver', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixspacegrey', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixssilver', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsspacegrey', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsgold', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsmaxsilver', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsmaxspacegrey', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixsmaxgold', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrproductred', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixryellow', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrwhite', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrcoral', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrblack', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chaixrblue', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11black', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11green', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11yellow', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11purple', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11productred', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11white', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11progold', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11prospacegray', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11prosilver', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promidnightgreen', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxgold', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxspacegray', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxsilver', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai11promaxmidnightgreen', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12black', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12white', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12productred', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12green', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12blue', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12purple', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniblack', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniwhite', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniproductred', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12minigreen', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12miniblue', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12minipurple', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12prosilver', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12prographite', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12progold', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12propacificblue', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxsilver', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxgraphite', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxgold', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai12promaxpacificblue', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13productred', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13starlight', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13midnight', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13pink', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13blue', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13green', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13miniproductred', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13ministarlight', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13minimidnight', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13miniblue', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13minipink', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13minigreen', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13prographite', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13progold', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13prosilver', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13prosierrablue', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13proalpinegreen', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxgraphite', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxgold', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxsilver', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxsierrablue', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai13promaxalpinegreen', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14midnight', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14purple', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14starlight', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14productred', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14blue', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14yellow', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusmidnight', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14pluspurple', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusstarlight', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusproductred', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusblue', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14plusyellow', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14prospaceblack', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14prosilver', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14progold', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14prodeeppurple', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxspaceblack', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxsilver', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxgold', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai14promaxdeeppurple', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15black', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15blue', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15green', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15yellow', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15pink', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusblack', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusblue', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusgreen', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15plusyellow', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15pluspink', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15problacktitanium', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15prowhitetitanium', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15probluetitanium', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15pronaturaltitanium', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxblacktitanium', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxwhitetitanium', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxbluetitanium', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('chai15promaxnaturaltitanium', 3, 2);

-- Glass
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6sblanca', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6snegra', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6splusblanca', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi6splusnegra', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7blanca', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7negra', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7plusblanca', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi7plusnegra', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8blanca', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8negra', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8plusblanca', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi8plusnegra', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gixnegra', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gixrnegra', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gixsmaxnegra', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi11negra', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi11pronegra', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi11promaxnegra', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi12negra', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi12mininegra', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi12promaxnegra', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi13negra', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi13mininegra', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi13promaxnegra', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14negra', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14plusnegra', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14pronegra', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi14promaxnegra', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15negra', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15plusnegra', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15pronegra', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi15promaxnegra', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16negra', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16plusnegra', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16pronegra', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16enegra', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('gi16promaxnegra', 7, 2);

-- Marco
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mcixnegra', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mcixsnegra', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mcixsmaxnegra', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci11pronegra', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci11promaxnegra', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci12negra', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci12mininegra', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci12promaxnegra', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13negra', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13mininegra', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13pronegra', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci13promaxnegra', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14negra', 9, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14plusnegra', 10, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14pronegra', 0, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci14promaxnegra', 1, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15negra', 2, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15plusnegra', 3, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15pronegra', 4, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci15promaxnegra', 5, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16negra', 6, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16promaxnegra', 7, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16pronegra', 8, 2);
INSERT INTO Componente (TIPO, STOCK, STOCK_MINIMO) VALUES ('mci16enegra', 9, 2);

SET SQL_SAFE_UPDATES = 1;