-- migracion-cliente.sql — Catálogo de clientes + vínculo con Telefono + concurrencia
USE gestion_reparaciones;

CREATE TABLE IF NOT EXISTS Cliente (
    ID_CLI     INT          NOT NULL AUTO_INCREMENT,
    NOMBRE     VARCHAR(150) NOT NULL,
    ACTIVO     BOOLEAN      NOT NULL DEFAULT TRUE,
    UPDATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_CLI)
);

ALTER TABLE Telefono
    ADD COLUMN ID_CLI INT NULL AFTER OBSERVACION,
    ADD COLUMN UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD CONSTRAINT fk_telefono_cliente FOREIGN KEY (ID_CLI) REFERENCES Cliente (ID_CLI);

INSERT INTO Cliente (NOMBRE, ACTIVO) VALUES ('WEB', TRUE), ('OTRO', TRUE);
